var analyseDescription = [
"GPU usage mode: 0 - none, 1 - for frame rendering. Should be used instead of \"super.gpu\" if and only if SVSuper is replaced with MSuper!",
"Direction of motion vectors to search for.<br/>1 - forward only, from current frame to the following one (not useful at all),<br/>2 - backward only, from following frame to the current one (useful only with \"smoothfps.algo: 1\"),<br/>3 - search both directions.",
"Size of a block (horizontal). It's either 8, 16 or 32. Larger blocks are less sensitive to noise, are faster, but also less accurate, smaller blocks produce more wavy picture.",
"Vertical size of a block. Default is equal to horizontal size. Additional options are: 4 for \"block.w:8\", 8 for \"block.w:16\", 16 for \"block.w:32\".",
"Block overlap value. 0 - none, 1 - 1/8 of block size in each direction, 2 - 1/4 of block size, 3 - 1/2 of block size. The greater overlap, the more blocks number, and the lesser the processing speed.Resulting overlap value in pixels should be even with CPU rendering.",
"Positive value is the number of levels used in the hierarchical analysis made while searching for motion vectors. Negative or zero value is the number of coarse levels NOT used in the hierarchical analysis made while searching for motion vectors.",
"The type of search on finest level:<br/>2 - Hexagon search, similar to x264,<br/>3 - Uneven Multi Hexagon (UMH) search, similar to x264,<br/>4 - Exhaustive search, slowest but it gives the best results.",
"Search range on finest level:<br/>0 - don't search on finest level at all, greatly increase search speed but may still looks good with GPU rendering. This option is opposite to \"super.pel\".<br/>>0 - classic fixed range in pixels.<br/><0 - \"adaptive\" range based on block local contrast. Range is small or zero for low contrast blocks (black/gray for example) but is big for blocks that has many visible details. Effective average range in common scenes is about 1/3 of this value.",
"Sort vectors from previous level by SAD values to define the order of blocks scanning so the search begins with better predictors. This option is always ON on coarse levels but may be time consuming on finest one.",
"Use SATD function instead of SAD on finest level. Extremely slow, do not use it!",
"Maximum width of a level to be processed with 'coarse' parameters. Can be useful to save CPU power when processing extra large frames (like UHD (4K)).",
"Same as 'main.search.type'.",
"Same as \"main.search.type\" except zero means \"-10\".",
"Use SATD function instead of SAD on every coarse level, improves motion vector estimation at luma flicker and fades.",
"Try to start searches around many predictors.",
"SAD threshold to define \"bad\" vectors. Value is scaled to block size 8x8.",
"The range of wide search for bad blocks. Use positive value for UMH search and negative for Exhaustive search.",
"Set the coherence of the field of vectors. The higher, the more coherent. However, if set too high, some best motion vectors can be missed.",
"penalty.lambda scaling mode between levels. 1.0 means no scaling, 2.0 - linear, 4.0 - quadratic dependence from hierarchical level number. This value is different from MVTools, see remark for explanations.",
"SAD limit for lambda using. Local lambda is smoothly decreased if SAD value of vector predictor is greater than the limit. It prevents bad predictors using but decreases the motion coherence. Value is scaled to block size 8x8.",
"Relative penalty (scaled to 256) to SAD cost for new candidate vector. New candidate vector must be better will be accepted as new vector only if its SAD with penalty (SAD + SAD*pnew/256) is lower then predictor cost (old SAD). It prevent replacing of quite good predictors by new vector with a little better SAD but different length and direction.",
"Relative penalty (scaled to 256) to SAD cost for global predictor vector (lambda is not used for global vector).",
"Relative penalty (scaled to 256) to SAD cost for zero vector. It prevent replacing of quite good predictor by zero vector with a little better SAD (lambda is not used for zero vector).",
"Relative penalty (scaled to 256) to SAD cost for up to 8 neighbours vectors.",
"Relative penalty (scaled to 256) to SAD cost for \"reverse\" vector (already found vector from reverse search direction), works only with \"analyse.vectors: 3\".",
"Only bad quality new vectors with SAD above this threshold will be re-estimated by search. Good vectors are not changed, but its SAD will be updated (re-calculated). Value is scaled to block size 8x8. Zero means \"do not refine, just divide\"",
"Same as main.search.type by default.",
"Same as super.pel value by default.",
"Same as main.search.satd by default.",
"Same as main.penalty.pnew by default.",
"Interval between analysed frames."]