var renderDescription = 
[
"Numerator of multiplier for frame rate change.",
"Denominator of multiplier for frame rate change.",
"If true then num/den define absolute frame rate value instead if multiplier for source frame rate.",
"Rendering algorithm or \"SVP shader\", available values are:<br/>1 - sharp picture without any blending, moves pixels by motion vectors from next frame to current. Requires only backward motion vectors (\"analyse.vectors: 2\") so it's the fastest possible method.<br/>2 - like 1st but moves pixels from the nearest (in terms of time) frame so it uses both backward and forward vectors. Recommended for 2D animations.<br/>11 - time weighted blend of forward and backward partial motion compensations.<br/>13 - same as 11th but with dynamic median added. Produces minimum artifacts but with noticeable halos around moving objects.<br/>21 - 11th plus additional cover/uncover masking to minimize halos and improve frame edges.<br/>23 - 21th plus extra vectors from adjacent frames for further decreasing of halos, can be less smooth than 21th.",
"Use block-based motion compensation instead of pixel-based. Always OFF with GPU rendering enabled.",
"Only works with GPU rendering enabled:<br/>0 - use bilinear interpolation for motion vectors and all masks,<br/>1 - use bicubic interpolation",
"Defines which video card should be used for rendering, only works with GPU rendering enabled:<br/>0 - default (use 1st available GPU),<br/>11 - use 1st GPU device on 1st OpenCL platfrom,<br/>12 - use 2nd GPU device on 1st OpenCL platfrom,<br/>21 - use 1st GPU device on 2nd OpenCL platfrom an so on.",
"Only works with GPU rendering enabled. When set to \"true\" frame rendering is done in linear light.",
"Cover/uncover mask strength, more means \"more strong mask\". Recommended values 50-100.",
"Bad areas (identified by vector's SAD values) mask, more means \"more strong mask\". Recommended value is 100, but it can dramatically reduce smoothness effect.",
"Defines the exponent of relation between SAD and area mask values.",
"Frames interpolation mode:<br/>0 - uniform interpolation for maximum smoothness. For example for 24->60 conversion output will be: \"1mmmm1mmmm...\", where \"1\" stands for original frame and \"m\" for interpolated one.<br/>1 - \"1m\" mode that gives \"1mm1m1mm1m...\" output in the above example => less artifacts at the cost of less smoothness.<br/>2 - \"2m\" mode: \"1m11m11m11...\" => much less artifacts and much less smoothness.<br/>3 - adaptive mode that switches between modes 0,1,2 based on overall vector field quality.",
"Blend frames at scene change like ConvertFps if true, or repeat last frame like ChangeFps if false.",
"Limit for changing uniform mode to \"1m\".",
"Limit for changing \"1m\" mode to \"2m\".",
"Limit for scene change detection.",
"Vectors with \"adjusted SAD\" less than this value are excluded from consideration.",
"Threshold which sets how many blocks in percents have to change.",
"Additional correction parameter for \"average luma\" value.",
"Screen aspect ratio defines black fields height (or width) and output video frame size.",
"Source video pixel aspect ratio.",
"\"Glow\" (or \"zoom out\") effect size, in percents of original frame size.",
"Lights count.",
"Flare length in percents.",
"Width of every light.",
"Height of averaging frame border.",]